name: Auto Deploy Server

on:
  push:
    branches:
      - main  # Замените "main" на вашу основную ветку

jobs:
  deploy:
    runs-on: ubuntu-latest  # Выберите нужное вам окружение

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install sshpass
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass

    - name: Deploy to Server      
      run: |
        sshpass -p "Dmitriy2840" ssh dmak@91.228.56.139 "echo Hello"
