name: Auto Deploy Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Create SSH directory
      run: mkdir -p ~/.ssh  # Создаем директорию ~/.ssh, если она не существует

    - name: Install SSH key
      run: |
        echo "$SSH_PRIVATE_KEY" > ssh_key.pem
        chmod 600 ssh_key.pem
        ssh-keyscan -H 91.228.56.139 >> ~/.ssh/known_hosts

    - name: Deploy to Server
      run: |
        # ssh -i ssh_key.pem dmak@91.228.56.139 "ls -l"
        cat ssh_key.pem
